apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "task_manager"
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "admin"
  PORT: "3000"
  NODE_ENV: "production"